### ISSUE TITLE
Make javaluator jigsaw compatible

### ISSUE THREAD

**Issue by dan323** [fathzer/javaluator#8]
**Is your feature request related to a problem? Please describe.**
When I try to import your library to my project, I get the warning to not publish as javaluator is not modular.

**Describe the solution you'd like**
I would like for module-info.java files be added, so that we can hava jigsaw compatible releases.

**Additional context**
Jigsaw has been releases since Java 9, and we are already at Java 21.

**Comment by dan323** [comment]
Created a PR changing to java 11 and add modularization: #9

**Comment by dan323** [comment]
@fathzer no more warnings in 3.0.5. You may close the MR and this issue.

**Comment by fathzer** [comment]
Hello @dan323 ,
Thank you very much for your help
